# Generated by Django 6.1 on 2026-08-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tracking",
            fields=[
                (
                    "tracking_no",
                    models.CharField(
                        help_text="来源: Section 3 Tracking Information 表格中的 Tracking No",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="追踪单号",
                    ),
                ),
                (
                    "logistics_company",
                    models.CharField(
                        help_text="来源: Section 3 Tracking Information 表格中的 Logistics Company",
                        max_length=64,
                        verbose_name="物流公司",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="Pending",
                        help_text="来源: 物流 API 返回的 current status 字段",
                        max_length=64,
                        verbose_name="物流状态",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="来源: 物流 API 返回的 last update 字段",
                        verbose_name="最后更新时间",
                    ),
                ),
            ],
            options={
                "verbose_name": "物流追踪",
                "verbose_name_plural": "物流追踪列表",
            },
        ),
    ]
