# Generated by Django 6.1 on 2026-08-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_no",
                    models.CharField(
                        help_text="来源: Order Details 表格中的 Order No 字段",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        verbose_name="订单编号",
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        help_text="来源: Order Details 表格中的 Order Date 字段",
                        verbose_name="订单日期",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="来源: Order Details 表格中的 Status 字段",
                        max_length=32,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="来源: Order Details 表格中的 Company Name 字段",
                        max_length=128,
                        verbose_name="公司名称",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        help_text="来源: Order Details 表格中的 Customer Name 字段",
                        max_length=128,
                        verbose_name="客户姓名",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="来源: Order Details 表格中的 Phone Number 字段",
                        max_length=32,
                        verbose_name="联系电话",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="来源: Order Details 表格中的 Email 字段",
                        max_length=254,
                        verbose_name="电子邮箱",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="来源: Order Details 表格中的 Address 字段",
                        verbose_name="配送地址",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单列表",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku_code",
                    models.CharField(
                        help_text="来源: SKU Details 表格中的 SKU 字段",
                        max_length=32,
                        verbose_name="SKU 编码",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="来源: SKU Details 表格中的 QTY 字段",
                        verbose_name="购买数量",
                    ),
                ),
                (
                    "tracking_no",
                    models.CharField(
                        blank=True,
                        help_text="来源: SKU Details 表格中的 Assigned Tracking 字段",
                        max_length=64,
                        null=True,
                        verbose_name="物流追踪单号/标识",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="来源: SKU Details 表格中的 Order # 外键关联",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="所属订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单项",
                "verbose_name_plural": "订单项列表",
            },
        ),
    ]
