# Generated by Django 6.1 on 2026-08-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "sku_code",
                    models.CharField(
                        help_text="来源: SKU Details & SQL 数据库中的 SKU 代码主键",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="SKU 编号",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="来源: Final Output 要求中的 Name 字段",
                        max_length=128,
                        verbose_name="商品名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="来源: Final Output 要求中的 Description 字段",
                        null=True,
                        verbose_name="商品描述",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="来源: Final Output 要求中的 Price per unit (Note: 价格已包含 GST)",
                        max_digits=10,
                        verbose_name="商品单价",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="来源: Section 2 Images for SKUs (真实图片 URL 或占位图 URL)",
                        null=True,
                        verbose_name="商品图片链接",
                    ),
                ),
            ],
            options={
                "verbose_name": "SKU 商品",
                "verbose_name_plural": "SKU 商品列表",
            },
        ),
    ]
